version: '3.4'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql

  worker1:
    image: worker:latest
    build:
      context: .
      dockerfile: Worker/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection="Server=TISED-042;Database=Assesment;Integrated Security=True;"

  worker2:
    image: worker:latest
    build:
      context: .
      dockerfile: Worker/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection="Server=TISED-042;Database=Assesment;Integrated Security=True;"

  worker3:
    image: worker:latest
    build:
      context: .
      dockerfile: Worker/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection="Server=TISED-042;Database=Assesment;Integrated Security=True;"

volumes:
  mssql-data:
